### ISSUE TITLE
Upgrade to VLLM 0.63

### ISSUE THREAD

**Issue by appoose** [mobiusml/aana_sdk#188]
vLLM version 0.60 is claiming a major uplift in speed and performance https://blog.vllm.ai/2024/09/05/perf-update.html . This is consistent to my observation in a runs in a100 instances in vastai and it supports multimodal better ( i.e. no particular version of transformers for models like Qwen-VL ). So suggest we upgrade to vllm-0.63 ( the latest pypi release at the time of writing or more )

**Comment by appoose** [comment]
@movchan74  thoughts?

**Comment by appoose** [comment]
Also the async engine works really well since they seperated out the server and api engine.

For example, much easier to generate streaming behaviour 

eg: 
```
engine_args=AsyncEngineArgs(model="Qwen/Qwen2-VL-2B-Instruct",    
                  limit_mm_per_prompt={'image': 3, 'video': 3},
                  gpu_memory_utilization=0.9)
vllm_vl_engine = AsyncLLMEngine.from_engine_args(engine_args)  
min_pixels = 224*224
max_pixels = 1024*1024
vl_model_processor = Qwen2VLProcessor.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct",
    min_pixels=min_pixels,
    max_pixels=max_pixels
)
```

```    
outputs_generator = vllm_vl_engine.generate(
      prompt={"prompt": text, "multi_modal_data": mm_data},
      sampling_params=SamplingParams(max_tokens=1024, temperature=0.0),
      request_id=str(uuid.uuid4()),
  )
  
  already_generated = 0 
  async for output in outputs_generator:
      generated_so_far = already_generated 
      already_generated = len(output.outputs[0].text)
      yield output.outputs[0].text[generated_so_far:]`

```

**Comment by movchan74** [comment]
We are already using 0.6. The main branch requires vllm>=0.6.1.post2 and poetry lock set to 0.6.2. I can update the poetry lock to 0.6.3 but we will not have any significant performance boost since we are already on 0.6.

Also, we have been using async API since the beginning.

**Comment by appoose** [comment]
Ok, then let us keep as it is. I will close the ticket
