### ISSUE TITLE
[ENHANCEMENT] Reuse stored data when the media id is the same 

### ISSUE THREAD

**Issue by ashwinnair14** [mobiusml/aana_sdk#68]
### Enhancement Description
- Overview of the enhancement
When the SDK gets a request to process a video, we should first check if we have any data of the video stored on the SDK and reuse it instead of reanalyzing the video. 

### Advantages
- Benefits of implementing this enhancement
Reduce the time needed to give results on videos previously processed.
Faster UX experience on the demo interface.

### Possible Implementation
- Suggested methods for implementing the enhancement

**Comment by ashwinnair14** [comment]
TBD

**Comment by movchan74** [comment]
@ashwinnair14  Is it related to the SDK or chat with video app? If chat with video app then didn't we fix it already?

**Comment by appoose** [comment]
It is already fixed in the chat with video app. So closing it for the time being.
