### ISSUE TITLE
Automation for store and delete cache files

### ISSUE THREAD

**Issue by HRashidi** [mobiusml/aana_sdk#82]
### Enhancement Description
- Overview of the enhancement
Currently if the test variables or deployment config is changed, the cache filed need to be recreated and stored inside the repo. But the old cache files will not be deleted automatically.

### Advantages
- Reduce the repo size
- Reduce the time for detecting unwanted files manually

### Possible Implementation
- Store cache files list required for tests and update it after running test via pytest. Then we can remove or add the cache files based on the list.

**Comment by movchan74** [comment]
Invalidated by https://github.com/mobiusml/aana_sdk/pull/151
